#!/usr/bin/env python

import os
from cuzk_tools.gpkg_parser import split_gpkg_into_files, USE_ORIGINAL_CATEGORIES


if __name__ == "__main__":
    gpkg_file_path = os.environ['HOME'] + "/.ros/cache/cuzk_tools/topography/data.gpkg"
    #get_layer_schemas(gpkg_file_path)
    split_gpkg_into_files(gpkg_file_path, 'topography', USE_ORIGINAL_CATEGORIES)

    #visualize_layer(gpkg_file_path,'BudovaJednotlivaNeboBlokBudov')