#!/usr/bin/env python

import rospy
import ros_numpy
import std_msgs

from sensor_msgs.msg import PointCloud2
from cuzk_tools.srv import GetElevationPcd,GetElevationPcdResponse

import pylas
import numpy as np
import os

from dmr5g import Dmr5gParser, WGS_TO_SJTSK

def is_file_in_dir(dir_path, fn):
    
    file_path = os.path.join(dir_path, fn)
    
    return os.path.exists(file_path)

class Elevation:
    def __init__(self):
        rospy.init_node('elevation')

        self.cache_dir = "/home/aherold/ws/src/cuzk_tools/cache/"
        self.elev_data_parser = Dmr5gParser(self.cache_dir, False)
        
        self.elev_pcd_pub = rospy.Publisher('elevation_pcd', PointCloud2, queue_size=10, latch=True)

        rospy.Service('elevation', GetElevationPcd, self.handle_elevation_service)

    def handle_elevation_service(self, req):
        # Assuming 'req' is of type GetElevationPcd, which contains 'point' and 'radius' fields.

        # Either the tile file has been downloaded previously and is stored in cache.
        radius = req.radius.data
        point = [req.point.x, req.point.y]
        ids = self.elev_data_parser.get_tile_ids(point, radius)

        pcd_data = None

        for id in ids:
            fn = self.elev_data_parser.get_tile_code(id) + ".laz"

            # Or we need to download it now.
            if not is_file_in_dir(self.cache_dir, fn):
                self.elev_data_parser.download_tile(id)

            tile_data = self.elev_data_parser.get_tile_data(fn)

            if pcd_data is None:
                pcd_data = np.copy(tile_data)
            else:
                pcd_data = np.concatenate((pcd_data,tile_data))

        point_sjtsk = WGS_TO_SJTSK.transform(point[1],point[0])
        dists = ((pcd_data['x'] - point_sjtsk[0])**2 + (pcd_data['y'] - point_sjtsk[1])**2)**(1/2)
        pcd_data = pcd_data[dists <= radius]

        pcd_data['x'] = pcd_data['x'] - np.mean(pcd_data['x'])
        pcd_data['y'] = pcd_data['y'] - np.mean(pcd_data['y'])
        pcd_data['z'] = pcd_data['z'] - np.mean(pcd_data['z'])

        msg = ros_numpy.msgify(PointCloud2, pcd_data)

        header = std_msgs.msg.Header()
        header.stamp = rospy.Time.now()
        header.frame_id = "sjtsk"

        msg.header = header

        self.elev_pcd_pub.publish(msg)

        # Return empty-ish response.
        response = GetElevationPcdResponse()
        return response


if __name__ == "__main__":
    node = Elevation()
    rospy.spin()
