#!/usr/bin/env python

"""
For more info see elecation_class.py.
"""

from elevation_class import Elevation
import rospy

if __name__ == "__main__":
    default_utm_zone = rospy.get_param('/elevation/default_utm_zone', None)
    node = Elevation(default_utm_zone)
    rospy.spin()
